new g_allow_change;
new g_giveflagadmin;
new g_join_show;
new g_features;
new g_min_player;
new g_see_text;
new g_serverid;
new g_debug;
new g_vip_type;
new g_time_point;
new g_replacePhrases;
new g_showpoints;
new g_levels;
new g_LevelPoints[100];
new g_WantFeature[120][MAXPLAYERS + 1];
new g_pointsnumber[MAXPLAYERS + 1];
new g_happynumber[MAXPLAYERS + 1];
new g_happyfactor[MAXPLAYERS + 1];
new g_playerpoints[MAXPLAYERS + 1];
new g_playerlevel[MAXPLAYERS + 1];
new g_points;
new g_createDatabase;
new g_extra_points;
new g_happyhouron;

new Float:g_infotime;

new String:g_admin_menu[32];
new String:g_LogFile[PLATFORM_MAX_PATH + 1];
new String:g_DebugFile[PLATFORM_MAX_PATH + 1];
new String:g_StammFolder[PLATFORM_MAX_PATH + 1];
new String:g_lvl_up_sound[PLATFORM_MAX_PATH + 1];
new String:g_Plugin_Version[10] = "2.04";
new String:g_tablename[64];
new String:g_texttowrite[32];
new String:g_texttowrite_f[32];
new String:g_viplist[32];
new String:g_viplist_f[32];
new String:g_viprank[32];
new String:g_viprank_f[32];
new String:g_sinfo[32];
new String:g_sinfo_f[32];
new String:g_schange[32];
new String:g_schange_f[32];
new String:g_sme[32];
new String:g_sme_f[32];
new String:g_StammTag[35];
new String:g_adminflag[3];

new bool:g_ClientReady[MAXPLAYERS + 1];
new bool:g_FeatureChange[120];
new bool:g_Pluginstarted;

new String:g_LevelName[100][128];
new String:g_FeatureBase[120][64];
new String:g_FeatureName[120][64];
new String:g_FeatureDesc[120][256];
new String:g_FeatureHaveDesc[120][100][256];
new g_FeatureLevel[120];
new g_FeatureEnable[120];
new Handle:g_HappyTimer;
